[package]
name = "rust-web3-basics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
web3 = "0.18.0"
tokio = "1.17.0"
dotenv = "0.15.0"
